from django.conf.urls.defaults import *

urlpatterns = patterns(
    'wowzer.asforums.views',
    (r'^$', 'index'),
    (r'^forum_collections/$', 'forum_coll_list'),
    (r'^forum_collections/(?P<forum_id>\d+)/$', 'forum_coll_detail'),
    (r'^forums/$', 'forum_list'),
    (r'^forums/create/$', 'forum_create'),
    (r'^forums/(?P<forum_id>\d+)/$', 'forum_detail'),
    (r'^forums/(?P<forum_id>\d+)/update/$', 'forum_update'),
    (r'^forums/(?P<forum_id>\d+)/delete/$', 'forum_delete'),
    (r'^forums/(?P<forum_id>\d+)/disc/$', 'forum_disc_list'),
    (r'^forums/(?P<forum_id>\d+)/disc/create/$', 'disc_create'),
    (r'^forums/(?P<forum_id>\d+)/disc/(?P<disc_id>\d+)/$', 'disc_detail'),
    (r'^forums/(?P<forum_id>\d+)/disc/(?P<disc_id>\d+)/update/$',
     'disc_update'),
    (r'^forums/(?P<forum_id>\d+)/disc/(?P<disc_id>\d+)/delete/$',
     'disc_detail'),
    (r'^forums/(?P<forum_id>\d+)/disc/(?P<disc_id>\d+)/posts/$',
     'disc_post_list'),
    (r'^forums/(?P<forum_id>\d+)/disc/(?P<disc_id>\d+)/posts/create/$',
     'post_create'),
    (r'^forums/(?P<forum_id>\d+)/disc/(?P<disc_id>\d+)/posts/(?P<post_id>\d+)/$',
     'post_detail'),
    (r'^forums/(?P<forum_id>\d+)/disc/(?P<disc_id>\d+)/posts/(?P<post_id>\d+)/update/$',
     'post_detail'),
    (r'^forums/(?P<forum_id>\d+)/disc/(?P<disc_id>\d+)/posts/(?P<post_id>\d+)/delete/$',
     'post_detail'),
    )
